### ISSUE TITLE
Two problems to run the model

### ISSUE THREAD

**Issue by kingofoz** [janivanecky/Depth-Estimation#1]
Hi @janivanecky 
1. Running test_depth.py will need eval_depth.py, but no this file in the project.
2. Beside the above, it still needs model_norm_abs_100k.prototxt, no this file. So I changed the name of net_deploy.prototxt to model_norm_abs_100k.prototxt. Not sure if this is OK.

Thanks,
Yingjun

**Comment by janivanecky** [comment]
Hi
1.) Thanks for pointing that out, I forgot to commit this script, it's in the repo now.
2.) Yes, that's right, either rename the prototxt file to model_norm_abs_100k.prototxt, or rename the model to net_deploy.caffemodel

Hope it works for you.

**Comment by kingofoz** [comment]
Thanks for the help! I will try it and let you know if I have further issues.
