### ISSUE TITLE
Can you share the source code of your modified caffe?

### ISSUE THREAD

**Issue by zhangshaoyong** [janivanecky/Depth-Estimation#10]
Hello, I am interested in your doctoral thesis. It is also interested in capturing depth information from a single image. I am a deep learning for beginners. I would like to refer to your modified Caffe source code. I wonder if it would be convenient for you to share it with me.
My email address is “zhangshaoyong@stu.ouc.edu.cn”
Thank you.

**Comment by janivanecky** [comment]
Hi, I haven't actually modified Caffe framework, so given the code in this repository, you should be able to run the training/inference using public Caffe release.

**Comment by zhangshaoyong** [comment]
@janivanecky My mean is I'd like to refer to the  modified loss layer code. 
Thank you.

**Comment by janivanecky** [comment]
Hi, I just used MVNLayer that is standard part of Caffe. I haven't used any custom layers.
