### ISSUE TITLE
How to get the absolute scale of the depth map ( such as unit in meter)?

### ISSUE THREAD

**Issue by JackHenry1992** [janivanecky/Depth-Estimation#11]
Thank you for share this perfect job very much!

In your thesis.pdf

![image](https://user-images.githubusercontent.com/9390228/30966178-9fe5fd00-a48a-11e7-94e1-b39453f35534.png)
Does it means that `output = net.blobs['depth-refine'].data` is the real absolute scale?
**I want to know how to get the true depth scale in meter.**

**Comment by janivanecky** [comment]
Hey! Sorry for the late response. 

> Does it means that output = net.blobs['depth-refine'].data is the real absolute scale?

In case of network trained with normalized loss, this output doesn't correspond to any real world scale. To get some sensible absolute values from the raw output, you have to multiply by some `s` and add some `m`. 

It's probably sufficient and something I should have done to just multiple by `s_t` which is standard deviation of the depth values in the training set and add `m_t` which is the mean depth value in the training set.
