### ISSUE TITLE
Can I use my data set while executing  test_depth.py

### ISSUE THREAD

**Issue by ipa-nhg-dd** [janivanecky/Depth-Estimation#12]
Can I use my data set while executing  test_depth.py, if yes how can i pass my images and i'm getting below mentioned result 
TOP 0 for AbsRelDiff

TOP 0 for SqrRelDiff

TOP 0 for RMSE

TOP 0 for RMSELog

TOP 0 for SIMSE

TOP 0 for Log10

TOP 0 for MVN

TOP 0 for Threshold 1.25

TOP 0 for Threshold 1.25^2

TOP 0 for Threshold 1.25^3

And also two directors created but no output in the folders

**Comment by JonathanCMitchell** [comment]
I believe you can input the images in the `INPUT_DIR` directory you specify with your command line arguments when running test_depth.py

**Comment by janivanecky** [comment]
@JonathanCMitchell is correct, additionally you should also pass directory with ground truth depth maps to the script.
