### ISSUE TITLE
get depth of new image

### ISSUE THREAD

**Issue by Jugaris89** [janivanecky/Depth-Estimation#15]
Hi,

I am trying to do inference of the trained model and get the depth of one of my images from KITTI dataset. 

I am not quite sure how to do it. I have tried creating firstly lmdb file with only my image and the running the get_depth script but it does not work.

I have been able to run process_test.sh that calculates the depth of the nyu_depth_v2_dataset but I am not sure how to do it on new images. 

Can you explain in detail please how could I obtain depth map of own image?

thanks

**Comment by janivanecky** [comment]
Hey! Sorry for the late response.

Have a look at `test_depth.py`. It should be what you're looking for.
