### ISSUE TITLE
Why crop the image?

### ISSUE THREAD

**Issue by LongLong-Jing** [janivanecky/Depth-Estimation#18]
@janivanecky 

Hi. Thanks for your great work. I have a question regarding the data processing. Why do you crop each image into the resolution of 561 x 427 in the process_row.m?

**Comment by jivanecky** [comment]
Hey! The cropping is part of tools provided with NYU Depth dataset, so I'm not sure about the reasoning for that.

**Comment by janivanecky** [comment]
Hey! The cropping is part of tools provided with NYU Depth dataset, so I'm not sure about the reasoning for that.

**Comment by LongLong-Jing** [comment]
@janivanecky  Thanks!
