### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by kingofoz** [janivanecky/Depth-Estimation#2]
Hi @janivanecky 
With your guide, I can run the code now. Thanks! However, there is a warning:
/usr/lib/python2.7/dist-packages/scipy/ndimage/interpolation.py:535: RuntimeWarning: invalid value encountered in true_divide
  zoom = (numpy.array(input.shape) - 1) / zoom_div

Does it matter?

By the way, why do we need ground truth depth map as an input? You know the goal is using the model to estimate depth map without providing ground truth depth map. 

Thanks,
Yingjun

**Comment by janivanecky** [comment]
Hi Yingjun,

I also get the warning, just ignore it. The test script is mainly meant to evaluate the performance of the model on the test set, so it needs ground truth. I cut out parts that were needed for performance evaluation and commited a new script - `get_depth.py`, which should do what you want. Hope it helps :)

**Comment by kingofoz** [comment]
I see. Thanks for the nice help! With get_depth.py, I can get a depth map in OUT_DIR_abs, but nothing in OUT_DIR. I guess this is correct, right?

**Comment by janivanecky** [comment]
Yep, that is correct, but not intended. I've already commited a modified script that doesn't create OUTPUT_DIR directory.

**Comment by kingofoz** [comment]
Got it. Thanks very very much for the help!
Can you please give me some instructions about training the model by my own dataset? Let me say some my understanding firstly.
1. Prepare train_raw2_color_298x218.lmdb: Resize my color images to 298 \* 218 and save them in a lmdb file. Is this correct?
2. Prepare train_raw2_depth_74x54.lmdb: Resize the relevant depth maps to 74 \* 54 and save them. Does a depth map need to have the same name with its relevant color image?
3. How to use AlexNet parameters and train the model?

Thanks!!
Yingjun

**Comment by janivanecky** [comment]
The training process is not that straightforward. The provided prototxt file contains definition of the whole model, but it's composed of 3 components. First 2 components are trained separately and after that their weights are fixed and the third part is trained on top of them. 
To address your questions about dataset:
1.) Yes, exactly
2.) Yes, you have to do this. Additionally, you also need to create depth maps of size 37x27 for training the first two components. Depth maps don't need to have the same name as corresponding rgb image, but they need to be stored in the same order in the LMDB.
3.) I think there are few ways you can achieve that, but I used python interface for that:

```
 solver = caffe.get_solver('solver.prototxt')
 solver.net.copy_from('bvlc_alexnet.caffemodel')
```

If you have more questions, feel free to ask :) (maybe checking out my [thesis](http://www.fit.vutbr.cz/study/DP/DP.php?id=18852&file=t), especially chapters 3, 4 will help you too)

**Comment by kingofoz** [comment]
I see. Thanks for the guide. It is very helpful to me. I am reading your thesis and will ask more questions. Thanks again!

Yingjun
