### ISSUE TITLE
dataset code

### ISSUE THREAD

**Issue by luohongcheng** [janivanecky/Depth-Estimation#5]

**Comment by janivanecky** [comment]
Hi, 
I'm going to respond to the original comment you entered, right now it looks like you edited out the whole thing. If it's no longer an issue, just say so.

I'm not sure which dataset you're using, but I used NYU Depth v2. The problem there is that raw data from camera and kinect aren't captured necessarily at the same moment and depth maps have blank areas with no depth values in them. What process_raw.m does, is finds the image-depthmap pairs that are closest to each other in time and fills in the holes. It does couple of other things too, but this is the main reason to use this script.

Hope it helps!

**Comment by luohongcheng** [comment]
Thank you very much !
