### ISSUE TITLE
Trained Caffe model not Found

### ISSUE THREAD

**Issue by sureajay** [janivanecky/Depth-Estimation#6]
Hi Janivanecky
I am not able to download the trained caffe model from the following link.
https://dl.dropboxusercontent.com/u/65091385/model_norm_abs_100k.caffemodel
Can you please provide an alternate link ?

Regards
Ajay

**Comment by janivanecky** [comment]
Hi, sorry for the late response:


There's been some change in Dropbox which I was not aware of. Here's a link that should work:

https://www.dropbox.com/s/rki8o74r7yv0k8d/model_norm_abs_100k.caffemodel?dl=0



Once again sorry and I hope it helps!


Cheers,

Jan


________________________________
