### ISSUE TITLE
miss folders in `split_train_set.sh` script 

### ISSUE THREAD

**Issue by vinthony** [janivanecky/Depth-Estimation#7]
Hi @janivanecky ,

Thanks for your work.

I try to use your code to get the train images from your code to NYU_Depth_V2 dataset.

but there are some miss folders in the raw dataset comparing to the results from `get_train_scenes.m`

such as: 'book_store0000' which is in the results of `get_train_scenes` and have no corresponding folder in the raw dataset. I download the split-file of raw datasets and the one-only file of the raw datasets, this folder doesn't exist in both datasets.

Do you have any ideas to solve this problem?

or just ignore this folder is ok?

I am looking forward to your response.

**Comment by janivanecky** [comment]
Hi!

I'm not sure if I had the same issue as you have, but I remember getting some similar errors during data processing. I definitely skipped a few images, but I have not inspected it thoroughly. If possible, check how many images would be missing if you were to ignore the error. If it's not substantial I wouldn't care about it.

**Comment by vinthony** [comment]
The script that I use creating 47k images which are almost the same with your pics in the thesis.
So I will ignore this small issue in this situation.
