### ISSUE TITLE
model trained on Kitti

### ISSUE THREAD

**Issue by ShervinAr** [janivanecky/Depth-Estimation#8]
Hello,
Thanks for sharing your work on depth estimation.
I am wondering whether you have performed any experiments on the kitti data set.
I particular I am interested to know if you could provide your model trained on kitti for a fair comprison in my research work.

many thanks

**Comment by janivanecky** [comment]
Hi, 
Sorry, but unfortunately I haven't done any experiments on KITTI, I don't have a machine set up to run the training and I don't have time to set everything up :/
